//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexUtility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApexUtility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1456962569_document_open {
            get {
                object obj = ResourceManager.GetObject("_1456962569_document_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1456962598_document_open {
            get {
                object obj = ResourceManager.GetObject("_1456962598_document_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1456962620_network_workgroup {
            get {
                object obj = ResourceManager.GetObject("_1456962620_network_workgroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1456962638_document_save {
            get {
                object obj = ResourceManager.GetObject("_1456962638_document_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1456962660_applications_internet {
            get {
                object obj = ResourceManager.GetObject("_1456962660_applications_internet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1456962679_resolutions_07 {
            get {
                object obj = ResourceManager.GetObject("_1456962679_resolutions_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1456962696_resolutions_19 {
            get {
                object obj = ResourceManager.GetObject("_1456962696_resolutions_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1456962709_resolutions_13 {
            get {
                object obj = ResourceManager.GetObject("_1456962709_resolutions_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1456962775_database_gear {
            get {
                object obj = ResourceManager.GetObject("_1456962775_database_gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^\s+)?--(\((\d+)\))(\s+)?(\&quot;\w+\{0\}\&quot;)(\s+)?\\\w+\\(\s+)?\[((\w|((?:\d*\.)?\d+))(-)?(-&gt;)?)+\](\s+)?(\\(case(:generate)?)?(-)?(refuse)?(-)?(class)?\\)?(\s+)?\{[\S\s]*?\}.
        /// </summary>
        internal static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^\s+)?\\AttributeSeperator(\s+)?\{(.)+\}.
        /// </summary>
        internal static string AttributeSeperator {
            get {
                return ResourceManager.GetString("AttributeSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^\s+)?\\CaseSeperator(\s+)?\{(.)+\}.
        /// </summary>
        internal static string CaseSeperator {
            get {
                return ResourceManager.GetString("CaseSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((\/\*)[\S\s]*?(\*\/))|((\/\/)[\S\s]*?(?=[\n\r])).
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^\s+)?\\End(\s+)?\{(.)+\}.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \{(.*?)\}.
        /// </summary>
        internal static string ExtractDescriptionAttribute {
            get {
                return ResourceManager.GetString("ExtractDescriptionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;(.*?)\&quot;.
        /// </summary>
        internal static string ExtractNameAttribute {
            get {
                return ResourceManager.GetString("ExtractNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \((.*?)\).
        /// </summary>
        internal static string ExtractPriorityOfAttribute {
            get {
                return ResourceManager.GetString("ExtractPriorityOfAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\(.*?)\\.
        /// </summary>
        internal static string ExtractTypeOfAttribute {
            get {
                return ResourceManager.GetString("ExtractTypeOfAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {(.)+\}.
        /// </summary>
        internal static string ExtractValue {
            get {
                return ResourceManager.GetString("ExtractValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \[(.*?)\].
        /// </summary>
        internal static string ExtractValueAttribute {
            get {
                return ResourceManager.GetString("ExtractValueAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^\s+)?\\MissingAttributeValues(\s+)?\{(.)+\}.
        /// </summary>
        internal static string MissingAttributeValues {
            get {
                return ResourceManager.GetString("MissingAttributeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^\s+)?\\Name(\s+)?\{(.)+\}.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^\s+)?\\NumberofAttributes(\s+)?\{(.)+\}.
        /// </summary>
        internal static string NumberofAttributes {
            get {
                return ResourceManager.GetString("NumberofAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^\s+)?\\NumberofClass(\s+)?\{(.)+\}.
        /// </summary>
        internal static string NumberofClass {
            get {
                return ResourceManager.GetString("NumberofClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {|}.
        /// </summary>
        internal static string RemoveBrace {
            get {
                return ResourceManager.GetString("RemoveBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \[|\].
        /// </summary>
        internal static string RemoveBracet {
            get {
                return ResourceManager.GetString("RemoveBracet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \(|\).
        /// </summary>
        internal static string RemoveParantesis {
            get {
                return ResourceManager.GetString("RemoveParantesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;|\&quot;.
        /// </summary>
        internal static string RemoveQutation {
            get {
                return ResourceManager.GetString("RemoveQutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\|\\.
        /// </summary>
        internal static string RemoveSlash {
            get {
                return ResourceManager.GetString("RemoveSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^\s+)?\\Title(\s+)?\{(.)+\}.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^\s+)?\\TestInstances(\s+)?\{(.)+\}.
        /// </summary>
        internal static string TestInstances {
            get {
                return ResourceManager.GetString("TestInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^\s+)?\\Title(\s+)?\{(.)+\}.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^\s+)?\\TrainingInstances(\s+)?\{(.)+\}.
        /// </summary>
        internal static string TrainingInstances {
            get {
                return ResourceManager.GetString("TrainingInstances", resourceCulture);
            }
        }
    }
}
